### ISSUE TITLE
custom namespace metrics don't show up?

### ISSUE THREAD

**Issue by mattcamp** [prometheus/cloudwatch_exporter#105]
Hi, 

I'm trying to use cloudwatch-exporter to pick up on some custom namespace cloudwatch metrics.

I've configured my config.yml as such:

```
region: eu-west-1
metrics:
- aws_namespace: provider_adapter
  aws_metric_name: declines
  aws_dimensions: [provider]
  aws_statistics: [Sum]
```

However it's just not showing up when I hit /metrics to test... cloudwatch_exporter_scrape_error is 0 and there aren't any signs of any errors... there's just nothing to suggest that the exporter has even picked up my config. The other config I have for standard AWS namespace metrics works fine.

I've verified the cloudwatch custom metric is available by connecting into the cloudwatch-exporter container, installing awscli and manually getting the metric data:

```
aws cloudwatch get-metric-statistics --namespace provider_adapter --metric-name declines --start-time 2018-06-06T00:00:00 --end-time 2018-06-06T12:00:00 --period 300 --statistics Sum --dimensions Name=provider,Value=ProviderNameX
{
    "Label": "declines",
    "Datapoints": [
        {
            "Timestamp": "2018-06-06T10:10:00Z",
            "Sum": 5.0,
            "Unit": "Count"
        },
        {
            "Timestamp": "2018-06-06T10:20:00Z",
            "Sum": 4.0,
            "Unit": "Count"
        },
        {
            "Timestamp": "2018-06-06T10:15:00Z",
            "Sum": 3.0,
            "Unit": "Count"
        }
    ]
}
```

Does cloudwatch-exporter even work with custom namespace metrics?

**Comment by brian-brazil** [comment]
It should work fine. Are you sure your data is within the 10-20m we usually look back?

**Comment by mattcamp** [comment]
Ahh maybe that's it... There haven't been any datapoints that recently. 

So the labels and metrics only appear in /metrics if there have actually been datapoints within the window?

A manual query for the last 30 minutes is returning:

```
{
    "Label": "declines",
    "Datapoints": []
}
```

**Comment by brian-brazil** [comment]
Yes, you can adjust the delay if needed. However such data may be too old to get ingested by Prometheus.

**Comment by suenfung** [comment]
I have a similar issue: I am trying to scrape metrics created by metrics filter from cloudwatch logs which do not have any dimension, and seems the exporter can fetch the metrics from aws service and didn't show any error logs.

**Comment by brian-brazil** [comment]
@suenfung That's a usage question, which is best brought up on prometheus-users. It's also a bit confusing to bring up unrelated issues on bugs.

**Comment by pankajmeesho** [comment]
@brian-brazil  So what is the solution of the problem reported by @suenfung ?

**Comment by pankajmeesho** [comment]
@brian-brazil  I have created some custom metrics in cloudwatch, for which value of the dimension is null. and cloudwatch exporter is not able to scrap the data.

sample: 
-  aws_namespace: AWS/LogMetrics
   aws_metric_name: NO-SUCH-KEY-ERROR
   aws_dimensions: []
   aws_statistics: [Sum]
   How can we get data for such cases using cloudwatch exporter.

**Comment by AceHack** [comment]
What is the solution here?

**Comment by seajon16** [comment]
Putting this here since this is the first page that popped up on google for me when I ran into this.

Something to watch out for is you must list every dimension the metric has under `aws_dimensions`, otherwise it won't be found. You don't need to do this when querying many of the standard AWS metrics since they are smart enough to [aggregate different metrics across dimensions](https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/cloudwatch_concepts.html#Dimension) if you don't specify enough of them. In addition, the standard metrics usually have multiple dimension combinations referring to the "same" piece of data (e.g. with Lambdas, there are two metrics with metric name `Invocations`: one with only `FunctionName` as a dimension, and one with both `FunctionName` and `Resource` as dimensions).

So, if you're using the default dimensions for custom metrics (at least with [AWS's python library](https://github.com/awslabs/aws-embedded-metrics-python)), at the bare minimum, you'll need something like this:
```
- aws_namespace: aws-embedded-metrics
  aws_metric_name: YourCustomMetricName
  aws_dimensions:
    - LogGroup
    - ServiceName
    - ServiceType
  aws_dimension_select:
    ServiceName:
      - "your_service_name"
  aws_statistics: [Sum]
```
