### ISSUE TITLE
How to Monitor  Rds with cloudwatch_exporter

### ISSUE THREAD

**Issue by AashishChughHome** [prometheus/cloudwatch_exporter#124]
Hi i am new in prometheus.
How to monitor rds with cloudwatch exporter.
I am using following config
But i don't know what i value i need to fill in aws_dimensions,aws_dimension_select,LoadBalancerName,aws_statistics

Can anyone please help.

region: us-east-2
metrics:
 - aws_namespace: AWS/RDS
   aws_metric_name: CPUUtilization
   aws_dimensions: [AvailabilityZone, LoadBalancerName]
   #aws_dimension_select:
    # LoadBalancerName: [myLB]
   #aws_statistics: [Sum]

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
