### ISSUE TITLE
CloudWatch Agent metrics not working

### ISSUE THREAD

**Issue by sujithpaily** [prometheus/cloudwatch_exporter#145]
All standard cloudwatch namespaces working fine. But I have a custom namespace using CWAgent not getting any data point. listMetris seems to show in cloudwatch_requests_total

- aws_namespace: AWS/CWAgent
  aws_metric_name: mem_used_percent
  aws_dimensions: [ImageId]
  aws_statistics: [Average]

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
