### ISSUE TITLE
CloudWatch agent metrics

### ISSUE THREAD

**Issue by sujithpaily** [prometheus/cloudwatch_exporter#146]
All standard namespaces working fine. But not getting metrics from Cloud watch agent. In cloudwatch it is showing under namespace 'CWAgent' with dimension [ImageId, InstanceId, InstanceType]. But following configs not working

- aws_namespace: AWS/CWAgent
  aws_metric_name: mem_used_percent
  aws_dimensions: [ImageId, InstanceId, InstanceType]
  aws_statistics: [Average]

- aws_namespace: AWS/CWAgent
  aws_metric_name: mem_used_percent
  aws_dimensions: [ImageId]
  aws_statistics: [Average]

cloudwatch_requests_total showing 
cloudwatch_requests_total{action="listMetrics",instance="10.221.5.187:9106",job="prometheus",namespace="AWS/CWAgent"}

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
