### ISSUE TITLE
Multiple dimension support

### ISSUE THREAD

**Issue by sujithpaily** [prometheus/cloudwatch_exporter#148]
Does  aws_dimension_select support multiple dimension?

I need to pass the following request using the cloud watch exporter config

aws cloudwatch get-metric-statistics --namespace "CWAgent" --metric-name "mem_used_percent" --dimensions Name=InstanceId,Value=i-03a1b963cd00a5cff Name=ImageId,Value=ami-0ac019f4fcb7cb7e6 Name=InstanceType,Value=t2.small --start-time 2018-10-20T08:40:00Z --end-time 2018-10-20T08:45:00Z --period 60 --statistics Average

**Comment by brian-brazil** [comment]
Yes, it's a map.

It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
