### ISSUE TITLE
prometheus graph have no data

### ISSUE THREAD

**Issue by redpangzi666** [prometheus/cloudwatch_exporter#162]
I use docker's method to install export.
To my surprise, Prometheus graph has graphics from above, but the console page no data.

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
