### ISSUE TITLE
 I want to monitor AWS RDS metrics in my prometheus , 

### ISSUE THREAD

**Issue by kondareddy103** [prometheus/cloudwatch_exporter#163]
Hello All ,

I want  to monitor my AWS RDS metrics in my prometheus , can any one help me how to  run rds-exporter in my kubernetes to  get the logs from cloud watch
Thanks in advance

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
