### ISSUE TITLE
Can't get AWS/DDoSProtection metrics

### ISSUE THREAD

**Issue by rafajurbano** [prometheus/cloudwatch_exporter#171]
Hi,

I'm trying get metrics of AWS/DDoSProtection namespace but I don't obtain results. My configuration is:

  - aws_namespace: AWS/DDoSProtection
    aws_metric_name: DDoSDetected
    aws_dimensions: [ResourceArn]

If I get the metrics via aws cli, I get all values. Have some idea about it?
Thanks!

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
