### ISSUE TITLE
exporter not running in us-west-2

### ISSUE THREAD

**Issue by cyrilbkr** [prometheus/cloudwatch_exporter#180]
Hi, 
I m trying to use this exporter on us-west-2 with Kubernetes but the pod do not run. I don't have any output log, the healthcheck of the pod failed and restart the pod. 

Everything works properly if I use another region like eu-west-1. 
Did i miss something ? 

Thanks guys

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
