### ISSUE TITLE
API gateway metrics are not showing /metrics

### ISSUE THREAD

**Issue by ramabalavfc** [prometheus/cloudwatch_exporter#187]
I have tried below configuration for API Gateway configuration, Metrics endpoint is not showing per API metrics, below is config, and CLI works for same set of metrics and dimensions.

 - aws_namespace: AWS/ApiGateway
  aws_metric_name: Latency
  aws_dimensions: [ApiName]
  aws_statistics: [Sum]

- aws_namespace: AWS/ApiGateway
  aws_metric_name: Count
  aws_dimensions: [ApiName]
  aws_statistics: [Sum]

- aws_namespace: AWS/ApiGateway
  aws_metric_name: 5XXError
  aws_dimensions: [ApiName]
  aws_statistics: [Sum]

- aws_namespace: AWS/ApiGateway
  aws_metric_name: 4XXError
  aws_dimensions: [ApiName]
  aws_statistics: [Sum]

please help on resolving the issue.

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
