### ISSUE TITLE
how to override few values present in config.yaml

### ISSUE THREAD

**Issue by polganesh** [prometheus/cloudwatch_exporter#199]
Hi ,
I want to override some values defined in config.yaml such as region and role_arn

not sure but is it possible for us to override it while running this container

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
