### ISSUE TITLE
Unable to scrape ReadThrottleEvents in AWS/DynamoDB

### ISSUE THREAD

**Issue by vijitha-ratnavel** [prometheus/cloudwatch_exporter#201]
Hello,

I am trying to scrape:
- aws_namespace: "AWS/DynamoDB"
  aws_metric_name: "ProvisionedReadCapacityUnits"
  aws_dimensions:
    - TableName
  aws_dimension_select_regex:
    TableName:
      - "(.*)prod(.*)"

- aws_namespace: "AWS/DynamoDB"
  aws_metric_name: "ReadThrottleEvents"
  aws_dimensions:
    - TableName
  aws_dimension_select_regex:
    TableName:
      - "(.*)prod(.*)"

I am able to see :
aws_dynamodb_provisioned_read_capacity_units_average | maximum | minimum |samplecount | sum. But nothing related to "ReadThrottleEvents". Can you please help?

Thanks

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

**Comment by vijitha-ratnavel** [comment]
Thanks @brian-brazil . Posted in news group.
