### ISSUE TITLE
unable to fetch metric for more namespaces or number of metric are more

### ISSUE THREAD

**Issue by polganesh** [prometheus/cloudwatch_exporter#209]
Hi,
I am able to fetch metric data from different account for application load balancer but when i try to fetch data for more namespaces or even if i try to add more metrics i am unable to do so. i received error like context deadline exceeded.
i tried increasing memory for docker container but it does not work. do we have any configuration/settings to avoid this error and fetch data for more and more namespaces

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
