### ISSUE TITLE
Prometheus dropped the cloudwatch explorer

### ISSUE THREAD

**Issue by papi83dm** [prometheus/cloudwatch_exporter#217]
I installed prometheus  and cloudwatch explorer in my eks cluster. When I look at the service discovered in prmetheus the cloudwatch explorer is being dropped and cloudwatch explorer does not shows up in the targets.

If I login to the container I can manually pull the metrics. Any idea why this explorer is being dropped? nothing is showing up in the prometheus server logs/

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
