### ISSUE TITLE
RDS CPU utilization not showing the correct value.

### ISSUE THREAD

**Issue by nirmal-nath** [prometheus/cloudwatch_exporter#218]
In my case, the **CPU utilization is only showing 0 and 1** but the CloudWatch is showing granular value like 0.2, 0.4, 0.6 0.8. Please look into this. Do let me know if you need further details.

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

**Comment by nirmal-nath** [comment]
Am guessing the issue is with the scraping of the cloudwatch exporter.
