### ISSUE TITLE
CloudWatch timestamp on Prometheus

### ISSUE THREAD

**Issue by ignasiduran** [prometheus/cloudwatch_exporter#226]
I scrape metrics from CloudWatch for ALB resource with the following configuration:

```
delay_seconds: 300
period_seconds: 60
range_seconds: 60
set_timestamp: true
```

The metrics are printed correctly, but with a delay of 6 minutes. ¿Is it possible to print the original CloudWatch timestamp on Prometheus with the "parameter set_timestamp: true"?

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
