### ISSUE TITLE
May I apply two account in one docker server

### ISSUE THREAD

**Issue by LuckyDogg** [prometheus/cloudwatch_exporter#232]
or apple two ak sk , My english is poor , can u understand my question ?

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
