### ISSUE TITLE
How can i add tags/labels in metrics ?

### ISSUE THREAD

**Issue by hunkjun** [prometheus/cloudwatch_exporter#242]
How can i add tags/labels in metrics ?  
example , add tags "project=public_one"
##### eg: 
aws_rds_database_connections_sum{job="aws_rds",instance="",dbinstance_identifier="rds001",} 16.0 1576558380000
##### to: 
aws_rds_database_connections_sum{job="aws_rds",project="public_one" instance="",dbinstance_identifier="rds001",} 16.0 1576558380000**

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
