### ISSUE TITLE
aws resource tag as label in prometheus metric

### ISSUE THREAD

**Issue by gangakrishh** [prometheus/cloudwatch_exporter#253]
I've this configuration and generated below metric

```
   - aws_namespace: AWS/SQS
      aws_metric_name: ApproximateNumberOfMessagesVisible
      aws_dimensions: [QueueName]
      aws_statistics: [Sum]
```
```
aws_sqs_approximate_number_of_messages_visible_sum{job="aws_sqs",instance="",queue_name="krish_sqs_test",} 0.0 1581449160000
```

can we able to get aws resource tag in promethues metric as label like below ?
```
aws_sqs_approximate_number_of_messages_visible_sum{job="aws_sqs",instance="",queue_name="krish_sqs_test",  tag="xyz-service" } 0.0 1581449160000
```

tag="xyz-service"

**Comment by gangakrishh** [comment]
cc'ing @brian-brazil  for notification

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

**Comment by gangakrishh** [comment]
Thanks @brian-brazil for advice
