### ISSUE TITLE
Minimum calls per unit of time and resource

### ISSUE THREAD

**Issue by aserrallerios** [prometheus/cloudwatch_exporter#256]
Hello,

I've raised the `scrape_interval` to `30m` and I've noticed that there's a minimum amount of calls that no matter the value for `scrape_interval` will be executed.

Is there any theoretical minimum of `GetMetricStatistics` and `ListMetrics` calls? Could that be configured or is it "hardcoded"?

Context: I'm trying to reduce the Cloudwatch costs as much as possible in dev/staging environments.

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
