### ISSUE TITLE
How to setup the exporter on Ubuntu Linux

### ISSUE THREAD

**Issue by tiagoIW** [prometheus/cloudwatch_exporter#266]
Hello, how are you ? I think this is not an issue, but a hole of information for noobs like me.

I'm starting with prometheus and I have no idea how to add new exporters to prometheus.

I read the README file of this exporter but I can't understood how to setup this exporter.

Someone could help me ?

Thanks!

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
