### ISSUE TITLE
aws_ebs metrics and instance label

### ISSUE THREAD

**Issue by dnull88** [prometheus/cloudwatch_exporter#270]
We have scraped aws_ebs_burst_balance_minimum metric from cloudwatch
`aws_ebs_burst_balance_minimum{job="aws_ebs",instance="",volume_id="vol-0692443b3429d1f",} 99.0 1588671900000`

The **instance** label is empty, so how to determinate which instance_id is use this ebs volume? any ideas?

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
