### ISSUE TITLE
No main manifest

### ISSUE THREAD

**Issue by tiagoIW** [prometheus/cloudwatch_exporter#272]
Hello, how are you ?

I'm getting this error when I try to run .jar

no main manifest attribute, in /usr/local/bin/cloudwatch_exporter.jar

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
