### ISSUE TITLE
Metrics offset value definition

### ISSUE THREAD

**Issue by snedi** [prometheus/cloudwatch_exporter#274]
In the Readme it is mentioned about the Timestamps:

```In practice this means that if you evaluate an instant vector at the current time, you will not see data from CloudWatch. An expression such as aws_elb_request_count_sum offset 10m will allow you to access the data, and should be used in recording rules and alerts.```

It is not clear if it is enough to choose any offset that just allows to fetch the values and see them in the query response or this offset should somehow be calculated based on some other parameters or data from CloudWatch?

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
