### ISSUE TITLE
delay_seconds: -20 What does this parameter mean

### ISSUE THREAD

**Issue by zhaijunming** [prometheus/cloudwatch_exporter#276]
delay_seconds: -20 ,  What does this parameter mean

Scrape the first metric and wait 20 seconds to scrape the second metric?

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

**Comment by refex** [comment]
I does not because a google search lead me here, not on the mainlist.

**Comment by matthiasr** [comment]
That is unfortunate, but we can work with it 😄 

For future visitors, the `delay_seconds` parameter is documented in the [README under Timestamps](https://github.com/prometheus/cloudwatch_exporter#timestamps). For more background on why this is necessary, see [this comment](https://github.com/prometheus/cloudwatch_exporter/issues/396#issuecomment-1003739270).
