### ISSUE TITLE
delay_seconds	  What do parameters mean

### ISSUE THREAD

**Issue by zhaijunming** [prometheus/cloudwatch_exporter#278]
Often restricted by AWS, When scraping data

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
