### ISSUE TITLE
aws_elb_un_healthy_host_count_average incorrect value

### ISSUE THREAD

**Issue by romanvog** [prometheus/cloudwatch_exporter#287]
Currently, we have a total of 10 unhealthy hosts specific ELB, all AZs together.
aws_elb_un_healthy_host_count_average metric returns 10 unhealthy hosts in each AZ

`aws_elb_un_healthy_host_count_average{load_balancer_name="foo",availability_zone="us-west-2c",} 10.0
aws_elb_un_healthy_host_count_average{load_balancer_name="foo",availability_zone="us-west-2b",} 10.0
aws_elb_un_healthy_host_count_average{load_balancer_name="foo",availability_zone="us-west-2a",} 10.0`

therefore, `sum by (load_balancer_name) (aws_elb_un_healthy_host_count_average{load_balancer_name="foo"})` returns 30, which is incorrect.

On the other hand, `aws_elb_healthy_host_count_average` returns just one value, without availability_zone label, and therefore returns a correct value.

Using cloudwatch_exporter-0.8.0 image

**Comment by brian-brazil** [comment]
We only return what Cloudwatch gives us. It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
