### ISSUE TITLE
Unable to query the metrics

### ISSUE THREAD

**Issue by skadem07** [prometheus/cloudwatch_exporter#288]
Is there a way to query the unhealthyHosts? I could not find a metric for unhealthyHosts?

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
