### ISSUE TITLE
How to Configure Scrape Duration

### ISSUE THREAD

**Issue by petrukngantuk** [prometheus/cloudwatch_exporter#290]
Hello, new user here

I want to configure `cloudwatch_exporter_scrape_duration_seconds` for all metrics to be 10 minutes, not in seconds,

can anyone show me how to do this?

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
