### ISSUE TITLE
AWS ES Metrics not being shown in the prometheus console.

### ISSUE THREAD

**Issue by papi83dm** [prometheus/cloudwatch_exporter#295]
For some reason this metric `aws_es_free_storage_space_average` doesn't show in the console, but it does show when I try to graph it. I also setup an alert on this metric and because it doesn't show it the console, prometheus can't trigger the alert.

![image](https://user-images.githubusercontent.com/1123681/89917683-15dcfb00-dbc7-11ea-96b7-80d72c4d2924.png)

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

**Comment by jan-ludvik-deltatre** [comment]
I also had this problem, coincidentally also with AWS/ES. The problem is described in this chapter: https://github.com/prometheus/cloudwatch_exporter#timestamps

Using `aws_es_cpuutilization_average offset 10m` solved my problem.
