### ISSUE TITLE
Do we need 2 config.yml for fetching metrics from 2 separate regions ?

### ISSUE THREAD

**Issue by m-mukesh** [prometheus/cloudwatch_exporter#309]
Hi..i have a scenario where i need to fetch ALB metrics from us-west-2 region, and also Cloudfront metrics. As per documentation, we need to specify region=us-east-1 for cloudfront metrics. But, as per the cloudwatch exporter docs, looks like we can specify only 1 region name in single config file. Please let me know whether we need 2 separate config files, and also do we need to create 2 cloudwatch-exporter services with separate ports like 9106, 9107 ?
Please guide me on this.

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
