### ISSUE TITLE
Custom CW Metrics not being exported

### ISSUE THREAD

**Issue by abc-dotcom** [prometheus/cloudwatch_exporter#312]
Hello

I´ve configured a Custom Cloudwatch Metric like this: cwexpo_custom_metrics is my custom namespace. But metrics are not getting exported. A quick help would be much appreciated.
aws_namespace: cwexpo_custom_metrics
aws_metric_name: mem_used_percent
aws_statistics: [Average]
aws_dimensions: [InstanceId]

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
