### ISSUE TITLE
Configuration to export cloudwatch logs metrics 

### ISSUE THREAD

**Issue by dicolasi** [prometheus/cloudwatch_exporter#319]
Hi all, 
can anyone show me how to export the logs attached in prometheus? In other words, what is the correct configuration in the values.yaml file?  So far I got the below (not much I know): 

```
region: eu-west-2
metrics:
  - aws_namespace: AWS/Logs
 [...] ?
```

Thanks
Simone

![Screenshot 2021-01-19 at 14 44 02](https://user-images.githubusercontent.com/54740533/105049682-d44d5780-5a64-11eb-847b-87730cde966a.png)

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

**Comment by dicolasi** [comment]
Wish you were right: https://groups.google.com/g/prometheus-users/c/aGY0WqqRlNU. Never been lucky with google groups that is why I created an issue here. Mind give me a direction?
