### ISSUE TITLE
Prometheus "Error on ingesting out-of-order samples"

### ISSUE THREAD

**Issue by asubram12** [prometheus/cloudwatch_exporter#347]
Prometheus is dropping metrics due to an "Error on ingesting out-of-order samples". I've verified that there is only one instance of cloudwatch-exporter running and there is a single service account. 

Deployment is done through helm with mostly default values for scraping ELB and RDS metrics. Listed below are some of the metrics. I don't see any duplicate metrics as well. 

```
# HELP aws_resource_info AWS information available for resource
# TYPE aws_resource_info gauge
# HELP cloudwatch_exporter_scrape_duration_seconds Time this CloudWatch scrape took, in seconds.
# TYPE cloudwatch_exporter_scrape_duration_seconds gauge
cloudwatch_exporter_scrape_duration_seconds 3.146966101
# HELP cloudwatch_exporter_scrape_error Non-zero if this scrape failed.
# TYPE cloudwatch_exporter_scrape_error gauge
cloudwatch_exporter_scrape_error 0.0
# HELP cloudwatch_requests_created API requests made to CloudWatch
# TYPE cloudwatch_requests_created gauge
cloudwatch_requests_created{action="listMetrics",namespace="AWS/RDS",} 1.61945554876E9
cloudwatch_requests_created{action="getMetricStatistics",namespace="AWS/ELB",} 1.619455541082E9
cloudwatch_requests_created{action="getMetricStatistics",namespace="AWS/RDS",} 1.619455548766E9
cloudwatch_requests_created{action="listMetrics",namespace="AWS/ELB",} 1.619455541023E9
```

**Comment by gogineni99** [comment]
This can happens when the timestamp of metric received is older than the metric that is already ingested (not due to duplicate metrics). Ex: If CW takes time to converge metrics, so if the exporter is not configured with enough delay_seconds, exporter might receive a metric at timestamp say 10:00 and in the next scrape it might receive a metric at 9:55. So, when prometheus tries to scrape the exporter the second time, it would throw this error.

I would suggest trying to increase delay_seconds config for exporter

**Comment by kamilhristov** [comment]
Try setting
```yaml
period_seconds: 60
````

https://github.com/prometheus-community/helm-charts/blob/main/charts/prometheus-cloudwatch-exporter/values.yaml#L93

**Comment by roee-landesman** [comment]
FWIW I found that setting `period_seconds` to 60 helped but did not increase the time enough to alleviate the root problem., but `300` did the trick.
