### ISSUE TITLE
Regarding cloudwatch_exporter collection values, data query issues after connecting to Prometheus

### ISSUE THREAD

**Issue by bruce202303** [prometheus/cloudwatch_exporter#610]
### Context information

* AWS service:
* CloudWatch namespace:
* Link to metrics documentation for this service:
* AWS region of the exporter:
* AWS region of the service:
![no-data](https://github.com/prometheus/cloudwatch_exporter/assets/127083946/8725371d-053a-4e2b-b9fe-258864ed89cc)
1.Why can’t I query the data in the table after connecting the data to Prometheus?

![image](https://github.com/prometheus/cloudwatch_exporter/assets/127083946/7cd0e333-0a6f-45f5-95aa-1872f21834f2)
2.However, there is data when querying under Graph, and there is a problem about time zone; I specified the area as ap-southeast-1 in the configuration file, but the default time zone of the data is still UTC.

<details>
    <summary>
        Exporter configuration
    </summary>

```yaml




```

</details>

<details>
    <summary>
        Exporter logs
    </summary>

```log

```

**Comment by matthiasr** [comment]
There are two separate things going on here:

* Prometheus keeps and (in its UI) shows [all data in UTC](https://prometheus.io/docs/introduction/faq/#can-i-change-the-timezone?-why-is-everything-in-utc). You can change the timezone in your dashboards for display purposes.
* CloudWatch data is often late, therefore the exporter by default only gets [values from 10 minutes ago](https://github.com/prometheus/cloudwatch_exporter#timestamps). An instant query "now" only looks back 5 minutes, that's why you don't see anything in the Table tab. Note how the lines in the graph view go flat 10 minutes ago (this is when real data ends) and extend by another 5 minutes (the lookback delta period).

Both are expected behavior.
