### ISSUE TITLE
Unable to fetch the DatabaseClass from the RDS cloudmetrics 

### ISSUE THREAD

**Issue by sree86** [prometheus/cloudwatch_exporter#98]
Hello ,
I am using thre following int he config.yml file

- aws_namespace: AWS/RDS
  aws_metric_name: DatabaseConnections
  aws_dimensions: [DBInstanceIdentifier, DatabaseClass]
  aws_statistics: [Sum]

I am not able to fetch the database class, please let me know if am missing anything from my side to get the yml file.

Thanks
Sreejith

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
